
export const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE';
export const START_INITIAL = 'START_INITIAL';
export const AUTO_LOAD = 'AUTO_LOAD';
export const START_CHAT = 'START_CHAT';
export const START_CHAT_FAILED = 'START_CHAT_FAILED';
export const TYPE_TEXT = 'TYPE_TEXT';
export const START_SENDING_MESSAGE = 'START_SENDING_MESSAGE';
export const MESSAGE_SENT = 'MESSAGE_SENT';

export const AGENT_FETCHED = 'AGENT_FETCHED';
export const USER_FETCHED = 'USER_FETCHED';


export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGE_SEND_DATA = 'MESSAGE_SEND_DATA';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_PAST_MESSAGES = 'LOAD_PAST_MESSAGES';

export const SHOW_TYPING = 'SHOW_TYPING';
export const HIDE_TYPING = 'HIDE_TYPING';

export const START_FILE_UPLOAD = 'START_FILE_UPLOAD';
export const FINISH_FILE_UPLOAD = 'FINISH_FILE_UPLOAD';
export const FILE_UPLOAD_PROGRESS = 'FILE_UPLOAD_PROGRESS';

export const TYPE_NAME = 'TYPE_NAME';
export const TYPE_EMAIL = 'TYPE_EMAIL';
export const USERFORM_VALIDATION = 'USERFORM_VALIDATION';
export const USERFORM_SKIP = 'USERFORM_SKIP';
export const USERFORM_SEND = 'USERFORM_SEND';